FROM php:8.4-cli-alpine AS test

RUN apk add --no-cache \
    autoconf \
    g++ \
    make \
    linux-headers \
    libstdc++ \
    brotli-dev \
    libzip-dev \
    openssl-dev

RUN docker-php-ext-install \
    pcntl \
    sockets \
    zip

RUN pecl channel-update pecl.php.net && \
    pecl install swoole && \
    docker-php-ext-enable swoole

RUN pecl install redis && \
    docker-php-ext-enable redis

WORKDIR /app

COPY composer.json ./
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer install \
    --optimize-autoloader

COPY . .
